name: daq
dependencies:
    - bokeh=0.12.4=py36_0
    - datashader=0.4.0=py36_0
    - holoviews=1.8.3=py36_0
    - jupyter=1.0.0=py36_3
    - matplotlib=2.0.2=np113py36_0
    - pandas=0.20.3=py36_0
    - python=3.6.2=0
    - scikit-learn=0.19.0=np113py36_0
    - scipy=0.19.1=np113py36_0
    - statsmodels=0.8.0=np113py36_0
    - tornado=4.4.2=py36_0
    - pip:
        - django==1.11.4
        - gatspy==0.3
        - gunicorn==19.7.1
        - mpld3==0.3
        - pandashells==0.1.8
        - seaborn==0.8.1
        - supersmoother==0.4
